//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppLimit.NetSparkle {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NetSparkleForm {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NetSparkleForm() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppLimit.NetSparkle.NetSparkleForm", typeof(NetSparkleForm).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.AnchorStyles similar to Bottom, Right.
        /// </summary>
        public static System.Windows.Forms.AnchorStyles buttonRemind_Anchor {
            get {
                object obj = ResourceManager.GetObject("buttonRemind.Anchor", resourceCulture);
                return ((System.Windows.Forms.AnchorStyles)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode buttonRemind_ImeMode {
            get {
                object obj = ResourceManager.GetObject("buttonRemind.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=236,Y=366}.
        /// </summary>
        public static System.Drawing.Point buttonRemind_Location {
            get {
                object obj = ResourceManager.GetObject("buttonRemind.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=110, Height=21}.
        /// </summary>
        public static System.Drawing.Size buttonRemind_Size {
            get {
                object obj = ResourceManager.GetObject("buttonRemind.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 1.
        /// </summary>
        public static int buttonRemind_TabIndex {
            get {
                object obj = ResourceManager.GetObject("buttonRemind.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remind me later.
        /// </summary>
        public static string buttonRemind_Text {
            get {
                return ResourceManager.GetString("buttonRemind.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode imgAppIcon_ImeMode {
            get {
                object obj = ResourceManager.GetObject("imgAppIcon.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=12,Y=11}.
        /// </summary>
        public static System.Drawing.Point imgAppIcon_Location {
            get {
                object obj = ResourceManager.GetObject("imgAppIcon.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=48, Height=48}.
        /// </summary>
        public static System.Drawing.Size imgAppIcon_Size {
            get {
                object obj = ResourceManager.GetObject("imgAppIcon.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.PictureBoxSizeMode similar to Zoom.
        /// </summary>
        public static System.Windows.Forms.PictureBoxSizeMode imgAppIcon_SizeMode {
            get {
                object obj = ResourceManager.GetObject("imgAppIcon.SizeMode", resourceCulture);
                return ((System.Windows.Forms.PictureBoxSizeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 0.
        /// </summary>
        public static int imgAppIcon_TabIndex {
            get {
                object obj = ResourceManager.GetObject("imgAppIcon.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool label3_AutoSize {
            get {
                object obj = ResourceManager.GetObject("label3.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Font similar to [Font: Name=Segoe UI, Size=9.75, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        /// </summary>
        public static System.Drawing.Font label3_Font {
            get {
                object obj = ResourceManager.GetObject("label3.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode label3_ImeMode {
            get {
                object obj = ResourceManager.GetObject("label3.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=66,Y=71}.
        /// </summary>
        public static System.Drawing.Point label3_Location {
            get {
                object obj = ResourceManager.GetObject("label3.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=96, Height=17}.
        /// </summary>
        public static System.Drawing.Size label3_Size {
            get {
                object obj = ResourceManager.GetObject("label3.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 3.
        /// </summary>
        public static int label3_TabIndex {
            get {
                object obj = ResourceManager.GetObject("label3.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release notes:.
        /// </summary>
        public static string label3_Text {
            get {
                return ResourceManager.GetString("label3.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool lblHeader_AutoSize {
            get {
                object obj = ResourceManager.GetObject("lblHeader.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Font similar to [Font: Name=Segoe UI, Size=9.75, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        /// </summary>
        public static System.Drawing.Font lblHeader_Font {
            get {
                object obj = ResourceManager.GetObject("lblHeader.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode lblHeader_ImeMode {
            get {
                object obj = ResourceManager.GetObject("lblHeader.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=66,Y=11}.
        /// </summary>
        public static System.Drawing.Point lblHeader_Location {
            get {
                object obj = ResourceManager.GetObject("lblHeader.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=218, Height=17}.
        /// </summary>
        public static System.Drawing.Size lblHeader_Size {
            get {
                object obj = ResourceManager.GetObject("lblHeader.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 5.
        /// </summary>
        public static int lblHeader_TabIndex {
            get {
                object obj = ResourceManager.GetObject("lblHeader.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version of APP is available!.
        /// </summary>
        public static string lblHeader_Text {
            get {
                return ResourceManager.GetString("lblHeader.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.AnchorStyles similar to Top, Left, Right.
        /// </summary>
        public static System.Windows.Forms.AnchorStyles lblInfoText_Anchor {
            get {
                object obj = ResourceManager.GetObject("lblInfoText.Anchor", resourceCulture);
                return ((System.Windows.Forms.AnchorStyles)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Font similar to [Font: Name=Segoe UI, Size=8.25, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        /// </summary>
        public static System.Drawing.Font lblInfoText_Font {
            get {
                object obj = ResourceManager.GetObject("lblInfoText.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode lblInfoText_ImeMode {
            get {
                object obj = ResourceManager.GetObject("lblInfoText.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=66,Y=36}.
        /// </summary>
        public static System.Drawing.Point lblInfoText_Location {
            get {
                object obj = ResourceManager.GetObject("lblInfoText.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=406, Height=35}.
        /// </summary>
        public static System.Drawing.Size lblInfoText_Size {
            get {
                object obj = ResourceManager.GetObject("lblInfoText.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 4.
        /// </summary>
        public static int lblInfoText_TabIndex {
            get {
                object obj = ResourceManager.GetObject("lblInfoText.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APP is now available (you have OLDVERSION). Would you like to download it now?.
        /// </summary>
        public static string lblInfoText_Text {
            get {
                return ResourceManager.GetString("lblInfoText.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.DockStyle similar to Fill.
        /// </summary>
        public static System.Windows.Forms.DockStyle NetSparkleBrowser_Dock {
            get {
                object obj = ResourceManager.GetObject("NetSparkleBrowser.Dock", resourceCulture);
                return ((System.Windows.Forms.DockStyle)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=0,Y=0}.
        /// </summary>
        public static System.Drawing.Point NetSparkleBrowser_Location {
            get {
                object obj = ResourceManager.GetObject("NetSparkleBrowser.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=389, Height=268}.
        /// </summary>
        public static System.Drawing.Size NetSparkleBrowser_Size {
            get {
                object obj = ResourceManager.GetObject("NetSparkleBrowser.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 0.
        /// </summary>
        public static int NetSparkleBrowser_TabIndex {
            get {
                object obj = ResourceManager.GetObject("NetSparkleBrowser.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.AnchorStyles similar to Top, Bottom, Left, Right.
        /// </summary>
        public static System.Windows.Forms.AnchorStyles panel1_Anchor {
            get {
                object obj = ResourceManager.GetObject("panel1.Anchor", resourceCulture);
                return ((System.Windows.Forms.AnchorStyles)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=69,Y=90}.
        /// </summary>
        public static System.Drawing.Point panel1_Location {
            get {
                object obj = ResourceManager.GetObject("panel1.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=393, Height=272}.
        /// </summary>
        public static System.Drawing.Size panel1_Size {
            get {
                object obj = ResourceManager.GetObject("panel1.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 9.
        /// </summary>
        public static int panel1_TabIndex {
            get {
                object obj = ResourceManager.GetObject("panel1.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.AnchorStyles similar to Bottom, Left.
        /// </summary>
        public static System.Windows.Forms.AnchorStyles skipButton_Anchor {
            get {
                object obj = ResourceManager.GetObject("skipButton.Anchor", resourceCulture);
                return ((System.Windows.Forms.AnchorStyles)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode skipButton_ImeMode {
            get {
                object obj = ResourceManager.GetObject("skipButton.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=69,Y=366}.
        /// </summary>
        public static System.Drawing.Point skipButton_Location {
            get {
                object obj = ResourceManager.GetObject("skipButton.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=110, Height=21}.
        /// </summary>
        public static System.Drawing.Size skipButton_Size {
            get {
                object obj = ResourceManager.GetObject("skipButton.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 2.
        /// </summary>
        public static int skipButton_TabIndex {
            get {
                object obj = ResourceManager.GetObject("skipButton.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip this version.
        /// </summary>
        public static string skipButton_Text {
            get {
                return ResourceManager.GetString("skipButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.AnchorStyles similar to Bottom, Right.
        /// </summary>
        public static System.Windows.Forms.AnchorStyles updateButton_Anchor {
            get {
                object obj = ResourceManager.GetObject("updateButton.Anchor", resourceCulture);
                return ((System.Windows.Forms.AnchorStyles)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode updateButton_ImeMode {
            get {
                object obj = ResourceManager.GetObject("updateButton.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=352,Y=366}.
        /// </summary>
        public static System.Drawing.Point updateButton_Location {
            get {
                object obj = ResourceManager.GetObject("updateButton.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=110, Height=21}.
        /// </summary>
        public static System.Drawing.Size updateButton_Size {
            get {
                object obj = ResourceManager.GetObject("updateButton.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 0.
        /// </summary>
        public static int updateButton_TabIndex {
            get {
                object obj = ResourceManager.GetObject("updateButton.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install update.
        /// </summary>
        public static string updateButton_Text {
            get {
                return ResourceManager.GetString("updateButton.Text", resourceCulture);
            }
        }
    }
}
